name: first-workflow
on: workflow_call
jobs:
    job1:
        uses: sahil4010/actions-pipeline/.github/workflows/reusable.yml@test
        with:
            version: 3.12

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
        -   name: get code
            uses: actions/checkout@v4

        -   name: dockerize
            run: |
                docker network create -d bridge two-tier
                docker build -t actions-pipeline .

                docker run -d \
                    --name mysql \
                    -v mysql-data:/var/lib/mysql \
                    --network=two-tier \
                    -e MYSQL_DATABASE=mydb \
                    -e MYSQL_ROOT_PASSWORD=admin \
                    -p 3306:3306 \
                    mysql:5.7

                docker run -d \
                    --name flaskapp \
                    --network=two-tier \
                    -e MYSQL_HOST=mysql \
                    -e MYSQL_USER=root \
                    -e MYSQL_PASSWORD=admin \
                    -e MYSQL_DB=mydb \
                    -p 5000:5000 \
                    actions-pipeline:latest
