name: first-workflow
on: [push, workflow_dispatch]
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -   name: get code
            uses: actions/checkout@v4

        -   name: dockerize
            run: |
                docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=devops -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin  -p 3306:3306   mysql:5.7
                docker build -t actions-pipeline .
                docker run actions-pipeline
