name: second-workflow
on: workflow_dispatch
jobs:
    using_actions-workflow:
      uses: sahil4010/actions-pipeline/.github/workflows/reusable.yml@test
      with:
        version: 3.12
    
    verify_multiple_call:
        runs-on: ubuntu-latest
        needs: using_actions-workflow
        steps:
        -   name: check
            run: echo "hello"
      
      
