name: second-workflow
on: push
jobs:
    job1:
      uses: sahil4010/actions-pipeline/.github/workflows/actions-workflow.yml@test
    
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
        -   name: check
            run: echo "hello"
      
      
